plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "E:\\Web\\akweb\\frontend\\src\\dist\\client"
publishOrigin = "ui"
commandOrigin = "ui"
base = "E:\\Web\\akweb\\frontend\\src"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]